apiVersion: v1
kind: Service
metadata:
  name: {{ include "admin-ui.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "admin-ui.selectorLabels" . | nindent 4 }}
