replicaCount: 1

image:
  repository: admin-ui
  tag: latest
  pullPolicy: IfNotPresent

env:
  REACT_APP_BASE_URL: "http://localhost:8085/web"
  REACT_APP_ENV: "development"

service:
  type: NodePort
  nodePort: 31723


ingress:
  enabled: false

serviceAccount:
  create: false
autoscaling:
  enabled: false